### ISSUE TITLE
Add prismlauncher

### ISSUE THREAD

**Issue by Lolothepro** [makedeb/prebuilt-mpr#1020]
### Package name

prismlauncher

### List any other notes that might aid in the inclusion of this package (Is the upstream/MPR package popular? Is the upstream well-known or from a reputable source?).

https://www.pcgamer.com/minecraft-launcher-project-spins-out-of-control-after-dev-hijacks-it-to-fight-leftist-queer-ideology/

`Prism Launcher was forked from PolyMC due to a sequence of actions by Lenny McLennington on the 17th of October, 2022. Lenny made several politically charged changes to the PolyMC GitHub repository and organization to remove those supporting "left-wing ideologies". In a commit, Lenny removed the PolyMC Code of Conduct, which outlined and prohibited discrimination against the LGBTQIA+ community and subsequently removed all maintainers. The commit and subsequent mass purge of maintainers were done without prior warning or discussion with the rest of the PolyMC team; the incident can be considered a hostile takeover.`

**Comment by hwittenborn** [comment]
I'll be at my computer in a bit, I'll get this added then. Definitely no objection to it.

**Comment by hwittenborn** [comment]
Just added the needed packaging, the packages should be deployed to the Prebuilt-MPR within an hour or so.

**Comment by Lolothepro** [comment]
![image](https://user-images.githubusercontent.com/68275908/197234262-ba90b47f-d4fe-4a10-aba9-337876fdbac4.png)

**Comment by hwittenborn** [comment]
It all got deployed yeah, just got busy with school and didn't get a chance to close this :p. Can confirm it's all good to go to install though

**Comment by hwittenborn** [comment]
Sounds great! Let me know if there's anything with it you need help with :)
