### ISSUE TITLE
Difference between rustc and rustup

### ISSUE THREAD

**Issue by joshcangit** [makedeb/prebuilt-mpr#1034]
These are more up-to-date and unified than the Ubuntu or Debian packages.

But, I noticed some difference between `rustc` and `rustup`.

**`cargo-miri`** is in **`rustc`** but not `rustup`.

**`rust-gdbgui`** is in **`rustup`** but not `rustc`.

Even so, I could add this using `rustup default stable`.
I could also add `rust-analyzer` component as well.
It's just slighty behind the latest version of `rustup`.

Both cannot be installed together.

The original `rustup` has both components.

**Comment by hwittenborn** [comment]
I didn't realize this was something that was included with Rust, it must've gone over my head or something. This is an issue with the `rustc` package on the MPR, right?

**Comment by joshcangit** [comment]
Thought that was also with the `rustup` package.

After installing it, the `rustc` got replaced and removed by this one.

**Comment by hwittenborn** [comment]
Hey @joshcangit, sorry for the wait on this, I've been quite busy with another project recently, and I haven't been able to get around to getting this done.

I'm gonna be done with the busy stuff on the other project within a week or so, then I'll get this looked at. If you'd want to look into getting both packages fixed I could help you get that done as well. Either way I'll make sure the issue gets fixed soon.

**Comment by joshcangit** [comment]
To me, a fix might be having only `rustup` and adding `cargo-miri`.

So far, this is 1 minor version behind the latest.
https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md

**Comment by hwittenborn** [comment]
Hey, sorry for the wait again @joshcangit, my notification inbox is quite flooded right now, and it's getting a bit hard for me to keep track of everything in it. I'm working on getting it cleaned out though.

I'll go ahead and get the `rustup` package fixed at least, I'll send a message once that's done.

**Comment by hwittenborn** [comment]
Sorry again for the wait, I've been quite busy with some other projects :P. I just did some local testing, and it looks like `cargo-miri` isn't a valid rustup component:

```sh
hunter@DESKTOP-MES71BQ:~/Documents/Git/GitHub/makedeb/makedeb$ cargo-miri 
error: the 'miri' component which provides the command 'cargo-miri' is not available for the 'stable-x86_64-unknown-linux-gnu' toolchain
```

Looking at the [Miri install instructions](https://github.com/rust-lang/miri#using-miri), it looks like Miri is available on Nightly, so it wouldn't be possible to include it in the `rustc` package. It'd probably be best to just remove `cargo-miri` from the Rustup package, right?

**Comment by joshcangit** [comment]
I've just checked the official `rustup` install for _default_ profile.
```
cargo
cargo-clippy
cargo-fmt
cargo-miri
clippy-driver
rls
rust-gdb
rust-gdbgui
rust-lldb
rustc
rustdoc
rustfmt
rustup
```

I don't think you should have less binaries than these.

**Comment by hwittenborn** [comment]
That's fair enough to include them in `rustup` since some of them can be in nightly rust releases. I'll add the things that are available to the `rustc` package, but yeah it won't be able to be all of them just because some aren't available on stable Rust.

**Comment by hwittenborn** [comment]
I managed to get this error out of `rustup` when making an invalid symlink to the `rustup` binary:

```sh
error: unknown proxy name: 'rust-analysis'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rust-gdbgui', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri', 'rustfmt', 'cargo-fmt'
```

It looks like that's everything you had listed (minus the `rustup` binary), so I'll go ahead and use that.

**Comment by joshcangit** [comment]
> ```sh
> error: unknown proxy name: 'rust-analysis'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rust-gdbgui', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri', 'rustfmt', 'cargo-fmt'
> ```

I wonder why you used the wrong name.
It's `rust-analyzer`.

**Comment by hwittenborn** [comment]
> I wonder why you used the wrong name.

I think I saw that `rust-analysis` was a component somewhere, I forget the exact reason.

> Also, `rust-analyzer` is not pre-installed and has to be added using `rustup component add rust-analyzer`.

Does that add any binary that needs exposed? If it does I'd prefer to add it, I wasn't able to find out if it does by adding the component though.

**Comment by joshcangit** [comment]
> > Also, `rust-analyzer` is not pre-installed and has to be added using `rustup component add rust-analyzer`.
> 
> Does that add any binary that needs exposed? If it does I'd prefer to add it, I wasn't able to find out if it does by adding the component though.

Unfortunately, no.
I had to make a script basically to wrap around `rustup run stable rust-analyzer`.
Can be written in Perl, Python or Ruby.
Maybe not Ruby since that's Ubuntu specific.

**Comment by hwittenborn** [comment]
Hey @joshcangit, I've been getting busy with school and haven't been able to put a ton of attention onto programming, so I've been working mostly on some core projects. Things are cooling down a bit now though, so I'm hoping to get back into the flow of everything real soon.

I don't recall if I asked, but do you want to just get the needed changes done yourself? If you'd have new PKGBUILDs for the rustup/rustc packages that you'd have tested I can just get those added real quick so we don't have to keep going back and forth

**Comment by joshcangit** [comment]
I kind of realized this issue isn't necessary for `rustup` since `cargo-miri` is only for nightly toolchain.
```
error: the 'miri' component which provides the command 'cargo-miri' is not available for the 'stable-x86_64-unknown-linux-gnu' toolchain
```

>  Also from the repository itself.
>  https://github.com/rust-lang/miri#using-miri

**Comment by hwittenborn** [comment]
Yeah it probably would be best to keep it out of the binaries exposed in `/usr/bin`, just because it could be removed in the future, or just something like how it's used being changed so a binary for it isn't available anymore. I think it'd be best to keep it out until it's available on a stable channel.

Was there anything else that needed changed then @joshcangit?

**Comment by joshcangit** [comment]
So far, it's adding `rust-gdbgui` to `rustc`.
