### ISSUE TITLE
add NodeJS LTS or remove node entirely to avoid overwriting NodeSource repo

### ISSUE THREAD

**Issue by cobalt2727** [makedeb/prebuilt-mpr#1048]
### Package name

nodejs

**Comment by hwittenborn** [comment]
What do mean by it's overwriting the NodeSource repo? Is there some version stuff between NodeSource and the PBMPR that's causing some version issue or something?

**Comment by cobalt2727** [comment]
Actually, I should probably close this down - looks like NodeJS 18 is now the LTS version... No idea when that happened, must've been recent :thinking:

I'll try switching my NodeSource repo to 18 later when I get some spare time, then try seeing if this conflicts with that. I'll reopen this if it's still an issue

> I don't think Node.js LTS has been packaged on the MPR yet, it'd need to be packaged on the MPR first before it got added here - Would you be willing to maintain that package yourself? I could help guide you through that process if you'd need it as well.

seeing as the current package apparently already _is_ the LTS release, it's probably best to just keep publishing that as the sole NodeJS package

**Comment by cobalt2727** [comment]
I dunno if this would be considered appropriate for the MPR, but you could technically just have the nodejs package run the NodeSource installer for whatever the current LTS is, with package updates to the makedeb package just pointing to newer versions of the installer script when the requirements get bumped up?
