### ISSUE TITLE
Updater does not distinguish between updates and additions

### ISSUE THREAD

**Issue by gamer4life1** [makedeb/prebuilt-mpr#682]
It would be nice if the updater could name PRs to distinguish updates or additions.

**Comment by hwittenborn** [comment]
What do think would be the benefit of doing such would be?

Either way you just have to review the build files and make sure they're all safe, nothing else should need to be done. Is there something else you're thinking of?

**Comment by hwittenborn** [comment]
Any update on this @gamer4life1? Do you think you still need it?
