### ISSUE TITLE
Improving uptimes for proget.makedeb.org to serve assets

### ISSUE THREAD

**Issue by devesh6s** [makedeb/prebuilt-mpr#702]
proget.makedeb.org CNAMED to proxy.hunterwittenborn.com hosted on linode is down. This is causing failures on our github codespaces devcontainers that rely heavily on prebuilt binaries available on https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub

@hwittenborn let us know if the community can help with the infrastructure / donate to extend the uptimes.

**Comment by lordofpipes** [comment]
Just a heads up, @hwittenborn has put proget.makedeb.org on new hosting that should hopefully be more stable. That being said, proget response latency still seems to be annoyingly high at times.
