### ISSUE TITLE
Helix

### ISSUE THREAD

**Issue by jakubrpawlowski** [makedeb/prebuilt-mpr#710]
Please add helix.

I saw there already was one: https://mpr.makedeb.org/packages/helix-bin

Thank you in advance! 🙇

**Comment by lordofpipes** [comment]
Looks alright, I've added `helix-bin`. It would be good to have a non `-bin` package as well if possible.

**Comment by jakubrpawlowski** [comment]
It appears it still isn't available. This is what it says on website:
<img width="514" alt="image" src="https://github.com/makedeb/prebuilt-mpr/assets/16911155/6ff0c342-b75f-4716-8300-8d8bf4d0ae0f">

And when I updated Dockerfile I get:

```
0.103 Reading package lists...
0.389 Building dependency tree...
0.472 Reading state information...
0.477 E: Unable to locate package helix-bin
------
```

and I do install other packages like `just` from prebuilt-mpr just fine. Am I doing it wrong?

**Comment by lordofpipes** [comment]
That part of the mprweb UI isn't working properly, but the package should be published to the repository: https://proget.makedeb.org/feeds/prebuilt-mpr?Search=helix-bin.

**Comment by jakubrpawlowski** [comment]
Ahh I see thank you - I think it's because I am on arm that it's not available.

**Comment by lordofpipes** [comment]
Yeah, aarch64 builds are possible on prebuilt-mpr, but the package has to be designed for it and not opt out of it by setting a specific architecture.
