### ISSUE TITLE
add polymc

### ISSUE THREAD

**Issue by DioEgizio** [makedeb/prebuilt-mpr#860]
### Package name

polymc

### List any other notes that might aid in the inclusion of this package (Is the upstream/MPR package popular? Is the upstream well-known or from a reputable source?).

PolyMC it's a pretty popular launcher/popular package on MPR

**Comment by hwittenborn** [comment]
Works for me. I'll be home later today and I'll get this added.

**Comment by hwittenborn** [comment]
Just added, it should be deployed to the Prebuilt-MPR shortly.
